# -*- coding: utf-8 -*-
"""DIP4_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrIExYua9XjsiBCixGSpKRotgZXs5oy3
"""

import numpy as np
import cmath
import matplotlib.pyplot as plt
import numpy as np
import string
import cv2
import random
from scipy import ndimage
import math

img = cv2.imread('input.png')
f = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
f=f.astype(np.float)
print(f)

winsiz=3
globvar=4

F=np.pad(f,((1,1),(1,1)), 'constant')

print(F)

print(f.shape,F.shape)

FF=np.zeros((F.shape[0],F.shape[1]))
print(int(winsiz/2),int(winsiz/2)+f.shape[1])
print(int(winsiz/2),int(winsiz/2)+f.shape[0])

for i in range(int(winsiz/2),int(winsiz/2)+f.shape[0]):
    for j in range(int(winsiz/2),int(winsiz/2)+f.shape[1]):
        
        tempa=F[(i-int(winsiz//2)):(i+int(winsiz//2)+1),(j-int(winsiz//2)):(j+int(winsiz//2)+1)]
        
        tempa=np.array(tempa)
        tvar=np.var(np.array(tempa))
        tmean=np.mean(np.array(tempa))
        
        if(globvar==0):
        
            FF[i][j]=F[i][j]
            
        
        elif(globvar<tvar):
        
            FF[i][j]=F[i][j]
            
        
        elif(globvar>tvar):
            FF[i][j]=tmean
            
        
        else:
            FF[i][j]=tmean

print(FF.shape)

Finalk=FF[1:570,1:761]
# Finalk=np.round(Finalk)
print(Finalk)

cv2.imwrite("Q3O.png",Finalk)

# img2 = cv2.imread('compar.png')
# f2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
# f2=f2.astype(np.float)
# print(f2)

# f2-Finalk

# import matplotlib.pyplot as plt

# tempimg = cv2.cvtColor(Finalk, cv2.COLOR_BGR2RGB)

# plt.imshow(Finalk)

