# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Raj Kamal Yadav
2016076
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysI6PVYJ5w-NlCA_3__-fuhrAxK0_jQK
"""

import numpy as np
import cmath
import matplotlib.pyplot as plt
import numpy as np
import string
import cv2
import random
from scipy import ndimage
import math

filter=[[1,1,1],[1,1,1],[1,1,1]]
filter=np.array(filter)
W=filter*(1/9)

img = cv2.imread('Chandrayaan2 - Q3a-inputimage.png')
f = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
f=f.astype(np.float)

print(f.shape)

f=f[:512,:512]

print(f.shape)

fpadx=W.shape[0]-1
fpady=W.shape[1]-1
wpadx=f.shape[0]-1
wpady=f.shape[1]-1

a=int((3-1)/2)
b=int((3-1)/2)

# f=np.pad(f, ((int(fpadx/2),int(fpadx-fpadx/2)),(int(fpady/2),int(fpady-fpady/2))), 'constant')

f=np.pad(f,(0,514-f.shape[0]),'constant')
w=np.pad(W, (0,511), 'constant',constant_values=(0,0))
# w=w[a:,b:]
print(f.shape,w.shape)

# for k in range(-1*a,a+1):
#     for l in range(-1*b,b+1):
#         m=k
#         n=l
#         if(k<0):
#             m=k %514
#         if (l<0):
#             n=l%514
#         w[m][n]=W[k+a][l+b]

print(f.shape,w.shape)

FF=np.fft.fft2(f)
WW=np.fft.fft2(w)
HH=np.multiply(FF,WW)
ZF=FF-HH

ZZF=FF+ZF
ZZZF=np.fft.ifft2(ZZF)
FImg=np.real(ZZZF)
Imgplt=FImg[:512,:512]

triop=0
for i in range(0,Imgplt.shape[0]):
    for j in range(0,Imgplt.shape[1]):
        if(Imgplt[i][j]<0):
            triop+=1
            Imgplt[i][j]=0
print(triop)

print(Imgplt.shape)

cv2.imwrite("unsharpmask.png",Imgplt)

